package core.basesyntax.dao.impl;

import core.basesyntax.AbstractTest;
import core.basesyntax.dao.SmileDao;
import core.basesyntax.model.Comment;
import core.basesyntax.model.Smile;
import core.basesyntax.model.User;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;

import java.util.List;

public class SmileDaoImplTest extends AbstractTest {
    private SmileDao smileDao;

    @Before
    public void setUp() {
        smileDao = new SmileDaoImpl(getSessionFactory());
    }

    @Override
    protected Class<?>[] entities() {
        return new Class<?>[]{
                Smile.class,
                Comment.class, // Добавляем Comment в список сущностей
                User.class // Добавляем User в список сущностей
        };
    }

    @Test
    public void create_Ok() {
        Smile funny = new Smile("funny");
        Smile actual = smileDao.create(funny);
        Assert.assertNotNull("Check you have implemented the `create` method " +
                "in the SmileDaoImpl class", actual);
        Assert.assertNotNull("ID for smile should be autogenerated", actual.getId());
    }

    @Test
    public void getAll_Ok() {
        Smile funny = new Smile("funny");
        Smile sad = new Smile("sad");
        Smile relieved = new Smile("relieved");
        Smile disappointed = new Smile("disappointed");

        smileDao.create(funny);
        smileDao.create(sad);
        smileDao.create(relieved);
        smileDao.create(disappointed);

        List<Smile> smiles = smileDao.getAll();
        Assert.assertNotNull("Smiles list should not be null", smiles);
        Assert.assertFalse("Smiles list should not be empty", smiles.isEmpty());
        Assert.assertEquals("Smiles list size should match the inserted entities", 4, smiles.size());
    }
}
